<?php
/**
 * Copyright © 2025 Everypay. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Everypay\Everypay\Block\Info $block */
$payment = $block->getInfo();
$paymentType = $payment->getAdditionalInformation('payment_type');
$methodTitle = $payment->getAdditionalInformation('method_title');
?>

<div class="payment-info-block">
    <?php if ($paymentType === 'IRIS'): ?>
        <p><strong><?= __('Payment Type') ?>:</strong> <?= __('IRIS Bank Payment') ?></p>
    <?php endif; ?>
</div>
