<?php
/**
 * @var \Everypay\Everypay\Block\Iris\Success $block
 */
$orderId = $block->getOrderIncrementId();
$customerEmail = $block->getCustomerEmail();
?>
<div class="checkout-success">
    <?php if ($orderId): ?>
        <p><?= $block->escapeHtml(__('Your order # is: %1.', $orderId)) ?></p>
        <p><?= $block->escapeHtml(__('We\'ll email you an order confirmation with details and tracking info.')) ?></p>
    <?php endif; ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= $block->escapeUrl($block->getContinueUrl()) ?>">
                <span><?= $block->escapeHtml(__('Continue Shopping')) ?></span>
            </a>
        </div>
    </div>

    <?php if ($customerEmail): ?>
        <div class="checkout-registration">
            <p><?= $block->escapeHtml(__('You can track your order status by creating an account.')) ?></p>
            <p><?= $block->escapeHtml(__('Email Address: %1', $customerEmail)) ?></p>
        </div>
    <?php endif; ?>
</div>
